(when (window-system)
  (setq-default line-spacing 2)
  (set-face-font 'default "MonacoB-15")
  (set-face-attribute 'default nil :weight 'bold)
  (set-fontset-font t 'hangul (font-spec :name "Nanum Gothic"))
  (add-to-list 'face-font-rescale-alist '("Arial Unicode MS" . 0.95))
  (add-to-list 'face-font-rescale-alist '("STIXGeneral" . 0.9))
  (add-to-list 'face-font-rescale-alist '("Nanum Gothic" . 0.95)))

(let ((alist '(( 33 . ".\\(?:\\(?:==\\|!!\\)\\|[!=]\\)")
                   ( 35 . ".\\(?:###\\|##\\|_(\\|[#(?[_{]\\)")
                   ( 36 . ".\\(?:>\\)")
                   ( 37 . ".\\(?:\\(?:%%\\)\\|%\\)")
                   ( 38 . ".\\(?:\\(?:&&\\)\\|&\\)")
                   ( 42 . ".\\(?:\\(?:\\*\\*/\\)\\|\\(?:\\*[*/]\\)\\|[*>]\\)") ; '*/' was deleted.
                   ( 43 . ".\\(?:\\(?:\\+\\+\\)\\|[+>]\\)")
                   ( 45 . ".\\(?:\\(?:-[>-]\\|<<\\|>>\\)\\|[<>}~-]\\)")
                   ( 46 . ".\\(?:\\(?:\\.[.<]\\)\\|[.=-]\\)")
                   ( 47 . ".\\(?:\\(?:\\*\\*\\|//\\|==\\)\\|[/=]\\)") ; '/*' and '/>' were deleted.
                   ( 48 . ".\\(?:x[a-zA-Z]\\)")
                   ( 58 . ".\\(?:::\\|[:=]\\)")
                   ( 59 . ".\\(?:;;\\|;\\)")
                   ( 60 . ".\\(?:\\(?:!--\\)\\|\\(?:~~\\|->\\|\\$>\\|\\*>\\|\\+>\\|--\\|<[<=-]\\|=[<=>]\\||>\\)\\|[*$+~<=>|-]\\)") ; '</' is deleted.
                   ( 61 . ".\\(?:\\(?:/=\\|:=\\|<<\\|=[=>]\\|>>\\)\\|[<=>~]\\)")
                   ( 62 . ".\\(?:\\(?:=>\\|>[=>-]\\)\\|[=>-]\\)")
                   ( 63 . ".\\(?:\\(\\?\\?\\)\\|[:=?]\\)")
                   ( 91 . ".\\(?:]\\)")
                   ( 92 . ".\\(?:\\(?:\\\\\\\\\\)\\|\\\\\\)")
                   ( 94 . ".\\(?:=\\)")
                   (119 . ".\\(?:ww\\)")
                   (123 . ".\\(?:-\\)")
                   (124 . ".\\(?:\\(?:|[=|]\\)\\|[=>|]\\)")
                   (126 . ".\\(?:~>\\|~~\\|[>=@~-]\\)"))))
      (dolist (char-regexp alist)
        (set-char-table-range composition-function-table (car char-regexp)
                              `([,(cdr char-regexp) 0 font-shape-gstring]))))

;; hangul
(set-language-environment "Korean")
(prefer-coding-system 'utf-8)
