services:
  nginx:
    image: nginx:latest
    container_name: pkg-proxy_nginx
    entrypoint: [ "/bin/bash", "-c" ]
    command: /usr/sbin/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public.crt:/self-sign.crt:ro
      - ./private.key:/self-sign.key:ro
    ports:
      - 4430:443
    restart: unless-stopped
    depends_on:
      - nexus

  nexus:
    image: sonatype/nexus3:latest
    container_name: pkg-proxy_nexus
    ports:
      - 8081:8081
    volumes:
      - ${DNEXUS_DATA}:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms128m -Xmx1024m -XX:MaxDirectMemorySize=1024m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    restart: unless-stopped
