services:
  nginx:
    image: nginx:latest
    container_name: pkg-proxy_nginx
    entrypoint: [ "/bin/bash", "-c" ]
    command: /usr/sbin/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./localhost.crt:/localhost.crt:ro
      - ./localhost.key:/localhost.key:ro
    ports:
      - 127.0.0.1:4430:443
    restart: unless-stopped
    depends_on:
      - nexus

  nexus:
    image: sonatype/nexus3:latest
    container_name: pkg-proxy_nexus
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - ${DNEXUS_DATA}:/nexus-data
    restart: unless-stopped
